version: '2.1'

services:

  mongo:
    container_name: aperium-mongo
    image: mongo:3.4
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dev123PWD
      - MONGO_INITDB_DATABASE=AperiumTrader
    volumes:
      - aperium-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - ctrader

  mynode:
    container_name: aperium-node
    build:
      context: .
      args:
        - NODE_ENV=development
    image: aperium-trader
    mem_limit: 3gb
    memswap_limit: 2gb
    mem_reservation: 1gb
    # restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
      #npm run start
#    healthcheck:
#      disable: true
    networks:
      - ctrader

  mongo-express:
    container_name: aperium-mongo-express
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123PWD
    networks:
      - ctrader
volumes:
  aperium-mongo:
networks:
  ctrader:
