version: '2.1'

services:

  mongo:
    container_name: aperium-mongo
    image: mongo:3.4
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dev123PWD
      - MONGO_INITDB_DATABASE=AperiumTrader
    volumes:
      - aperium-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - ctrader

  loader-node:
    container_name: aperium-loader
    build:
      context: ./loader
      args:
        - NODE_ENV=development
    image: aperium-loader
    mem_limit: 2gb
    memswap_limit: 1gb
    mem_reservation: 1gb
    ports:
      - "5000:5000"
    volumes:
      - ./loader:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
    networks:
      - ctrader

  planner-node:
    container_name: aperium-planner
    build:
      context: ./planner
      args:
        - NODE_ENV=development
    image: aperium-planner
    mem_limit: 2gb
    memswap_limit: 1gb
    mem_reservation: 1gb
    ports:
      - "6000:6000"
    volumes:
      - ./planner:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
    networks:
      - ctrader

  mongo-express:
    container_name: aperium-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123PWD
    networks:
      - ctrader
volumes:
  aperium-mongo:
networks:
  ctrader:
