version: '2.1'

services:

  mongo:
    container_name: aperium-mongo
    image: mongo:3.4
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dev123PWD
      - MONGO_INITDB_DATABASE=AperiumTrader
    volumes:
      - aperium-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - ctrader

  loadernode:
    container_name: loader
    build:
      context: ./loader
      args:
        - NODE_ENV=development
    image: trader-loader
    mem_limit: 2gb
    memswap_limit: 1gb
    mem_reservation: 1gb
    ports:
      - "5000:5000"
    volumes:
      - ./loader:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
    networks:
      - ctrader

  plannernode:
    container_name: planner
    build:
      context: ./planner
      args:
        - NODE_ENV=development
    image: trader-planner
    mem_limit: 2gb
    memswap_limit: 1gb
    mem_reservation: 1gb
    ports:
      - "6000:6000"
    volumes:
      - ./planner:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
    networks:
      - ctrader

  executernode:
    container_name: executer
    build:
      context: ./executer
      args:
        - NODE_ENV=development
    image: trader-executer
    mem_limit: 2gb
    memswap_limit: 1gb
    mem_reservation: 1gb
    ports:
      - "7000:7000"
    volumes:
      - ./executer:/usr/src/app
    environment:
      - NODE_ENV=development
    command: node --max-old-space-size=2048 index.js
    networks:
      - ctrader

  nginxweb:
    container_name: webserver
    build:
      context: ./aperiumwww
      args:
        - NODE_ENV=development
    image: aperium-web
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    networks:
      - ctrader

volumes:
  aperium-mongo:
networks:
  ctrader:
